sudo: required
services:
  - docker

before_install:
  - docker build -t firuciak/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true firuciak/react-test npm test

after_success:
  - docker build -t firuciak/multi-client -f ./client
  - docker build -t firuciak/multi-nginx -f ./nginx
  - docker build -t firuciak/multi-server -f ./server
  - docker build -t firuciak/multi-worker -f ./worker
# log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# take those images and push them to docker hub
  - docker push firuciak/multi-client
  - docker push firuciak/multi-nginx
  - docker push firuciak/multi-server
  - docker push firuciak/multi-worker